version: '3.8'

services:
  # 1. MongoDB 엔진
  mongodb:
    image: mongo:latest
    container_name: pitwall_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ID}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
    ports:
      - "27017:27017"
    volumes:
      # - ./data/mongo_db:/data/db  <-- 윈도우 폴더랑 연결해서 에러 남
      # [수정 후] 도커 전용 볼륨 사용 -> 도커 환경은 WSL인데 데이터 저장 폴더가 Window인 경우 충돌 발생
      - mongo_data:/data/db

  # 2. Mongo Express (GUI)
  mongo-express:
    image: mongo-express
    container_name: pitwall_mongo_ui
    restart: always
    ports:
      - "8088:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ID}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PW}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ID}:${MONGO_PW}@mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb


  # 3. Qdrant 벡터 데이터베이스
  qdrant:
    image: qdrant/qdrant:latest
    container_name: pitwall_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage # 데이터 영구 저장
    restart: always
    

# [NEW] 볼륨 정의 추가 (맨 아래에 이거 꼭 추가!)
volumes:
  mongo_data: